apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-multi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-multi
  template:
    metadata:
      labels:
        app: kube-multi
    spec:
      containers:
      - name: frontend
        image: nginx:stable
        ports:
          - containerPort: 80
        volumeMounts:
          - name: frontend-html
            mountPath: /usr/share/nginx/html
      - name: backend
        image: php:7.4-apache
        ports:
          - containerPort: 80
        volumeMounts:
          - name: backend-php
            mountPath: /var/www/html/guestbook.php
            subPath: guestbook.php
      volumes:
        - name: frontend-html
          configMap:
            name: kube-frontend-html
        - name: backend-php
          configMap:
            name: kube-backend-php
