apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-multi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-multi
  template:
    metadata:
      labels:
        app: kube-multi
    spec:
      containers:
      - name: frontend
        image: nginx:stable
        ports:
          - containerPort: 80
        volumeMounts:
          - name: frontend-html
            mountPath: /usr/share/nginx/html
      - name: backend
        image: php:7.4-apache
        ports:
          - containerPort: 8080
        env:
        - name: APACHE_LISTEN_PORT
          value: "8080"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
        command: ["/bin/sh", "-c"]
        args:
          - |
            sed -i 's/Listen 80/Listen 8080/g' /etc/apache2/ports.conf
            sed -i 's/:80>/:8080>/g' /etc/apache2/sites-available/000-default.conf
            apache2-foreground
        volumeMounts:
          - name: backend-php
            mountPath: /var/www/html/guestbook.php
            subPath: guestbook.php
          - name: dbcreds
            mountPath: /var/www/dbcreds.php
            subPath: dbcreds.php
      volumes:
        - name: frontend-html
          configMap:
            name: kube-frontend-html
        - name: backend-php
          configMap:
            name: kube-backend-php
        - name: dbcreds
          configMap:
            name: dbcreds-php
